name: deploy

on:
  push:
    branches:
      - main

env:
  SECRET_KEY: "test-secret-key"
  SQLALCHEMY_DATABASE_URL: "sqlite:///./test.db"
  AWS_REGION: ap-northeast-1
  ECS_CLUSTER: watanabe-fastapi-cluster
  ECS_SERVICE: watanabe-fastapi
  ECR_REPOSITORY: watanabe-fastapi
  ECS_TASK_DEFINITION_API: .aws/task-def-api.json

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run tests
        run: uv run pytest tests/test_user.py
  

  build:
    needs: test
    runs-on: ubuntu-latest

    outputs:
      image_uri: ${{ steps.push-image.outputs.image_uri }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Build an Image
        run: docker image build -t temp_usermanagement_api_image:latest .
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Push the image to Amazon ECR
        id: push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker image tag temp_usermanagement_api_image:latest $IMAGE_URI
          docker image push $IMAGE_URI
          echo "image_uri=$IMAGE_URI" >> "$GITHUB_OUTPUT"
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      
      - name: Define the image URI
        run: |
          echo "API_IMAGE_URI=$(cat artifacts/api-image-uri.txt)" >> $GITHUB_ENV
      
      - name: Fill in the new image URI in the amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_API }}
          container-name: watanabe-fastapi
          image: ${{ needs.build.outputs.image_uri }}
    
      - name: Deploy ECS task
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
          


